name: Update Game List

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_PUSH || github.token }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run script
        run: bun run scrapper.js

      - name: Commit and push changes
        run: |
          git config --local user.email "nicolasgabrieltomasin@gmail.com"
          git config --local user.name "NicoTomasin"
          git add gameNames.json
          if ! git diff --staged --quiet; then
            git commit -m "Update Game List"
            git push
          else
            echo "No changes to commit"
          fi
